### ISSUE TITLE
Unexpected typing of `columnnames`?

### ISSUE THREAD

**Issue by bertrand-caron** [JuliaData/TypedTables.jl#59]
Hi,

I am a bit confused by the typing of `columnnames()`.

See the example below:

```
>using TypedTable
>t1 = Table(a=[1,2,3])
>typeof(columnnames(t1))
Tuple{Symbol}
>t2 = Table(a=[1,2,3], b=[2,3,4])
>typeof(columnnames(t2))
Tuple{Symbol,Symbol}
```

I would expect the type of `columnnames()` to be independent of its input (most likely a `Vector{Symbol}`).

Is this a feature or a bug?

**Comment by bertrand-caron** [comment]
@andyferris :)

**Comment by andyferris** [comment]
Feature! TypedTables (like StaticArrays) is all about a putting information into the types so they propagate through compilation resulting in more optimazation than you would normally get (in this case, with a DataFrame). 

A tuple with N elements is a bit like a Vector, except the number of elements is known by the compiler and the compiler can identify the type of each of the elements. A tuple can be inlined and stored on the stack, while a Vector cannot.

TypedTables uses tuples (and named tuples) extensively throughout to get this benefit - but it is hard on the compiler. On the other hand, if you have a large number of columns (or you don’t know the types of your columns) a DataFrame could be better (definitely for compiler time, and maybe even run time). 

Keep in mind you always get a `Tuple{Vararg{Symbol}}` back from this function.

**Comment by andyferris** [comment]
@bertrand-caron I will close this now
