### ISSUE TITLE
`resize!(::Table, ::Int)` is not defined

### ISSUE THREAD

**Issue by junyuan-chen** [JuliaData/TypedTables.jl#60]
The following usage leads to an error, which is unexpected.

     using TypedTables
     t = Table(a=collect(1:100))
     sort(t)

     ERROR: MethodError: no method matching resize!(::Table{NamedTuple{(:a,),Tuple{Int64}},1,NamedTuple{(:a,),Tuple{Array{Int64,1}}}}, ::Int64)

The above is produced with TypedTables v1.2.0 in Julia 1.5.0 on a Mac.

No error occurs if I use a short column, say, with only 10 rows.

**Comment by andyferris** [comment]
That’s interesting - I don’t think I’ve run `sort` on it directly before. We should definitely support this and make this work. 

In the meanwhile you can call `sortperm` on the the column in question and use indexing (or perhaps `permute!`), like `table[sortperm(table.a))`.

**Comment by junyuan-chen** [comment]
By the way, `accelerate!(a, SortIndex)` calls `sort!(a)`. I ran into this issue when I was trying to accelerate a TypedTable.

**Comment by andyferris** [comment]
Yes - OK. I haven't yet extended that API to work on tables, generally you'd run `accelerate` or `accelerate!` on a column.

**Comment by andyferris** [comment]
The underlying issue here seems to be `resize!` not being defined, which is unfortunate since we have `push!` etc. I'll try take a look at that.
