### ISSUE TITLE
New release is not tagged due to inactive TagBot

### ISSUE THREAD

**Issue by junyuan-chen** [JuliaData/TypedTables.jl#63]
It has been several days since the release of version 1.2.1. However, no git tag is made for this release because TagBot is inactive.

Please update to the new TagBot settings as explained in the post below:
https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249

Thanks!

**Comment by quinnj** [comment]
I think [this commit](https://github.com/JuliaData/TypedTables.jl/commit/5321692f7fc7cf8d0eb9a16f404a42ec2d82d636) should fix it

**Comment by junyuan-chen** [comment]
@quinnj  Hi, I think you also need to manually trigger the TagBot action once for v1.2.1.

See #62. It seems that the TagBot comment used to trigger the GitHub action only works when the correct settings are there before the release process starts.
