### ISSUE TITLE
Support Adapt.jl for GPU support

### ISSUE THREAD

**Issue by oschulz** [JuliaData/TypedTables.jl#65]
Would be very nice to be able to push a `Table` to a GPU.

Would a PR be welcome?

**Comment by quinnj** [comment]
Probably? What kind of change does it involve?

**Comment by oschulz** [comment]
It should be very simple, in StructArrays for example, it's just this
(see https://github.com/JuliaArrays/StructArrays.jl/blob/0b82933aedcc6c62ff46cf36dc0bc026d366151d/src/StructArrays.jl#L27):

```julia
import Adapt
Adapt.adapt_structure(to, s::StructArray) = replace_storage(x->Adapt.adapt(to, x), s)
```

Adapt.jl is extemely lightweight and has no dependencies itself (purposefully), so adding it to the deps of TypedTables will not impact the package load time and introduce no maintenance hassle either..

**Comment by andyferris** [comment]
Yes - I think should be fine.

**Comment by oschulz** [comment]
Ok, I'll get on it, then. :-)

**Comment by oschulz** [comment]
Here we go: #67

**Comment by andyferris** [comment]
This was merged.

**Comment by oschulz** [comment]
Sorry, forgot to close it.
