### ISSUE TITLE
Error in reproducing filter example from documentation

### ISSUE THREAD

**Issue by PatMcFarlane** [JuliaData/TypedTables.jl#79]
I'm using Julia 1.6.1 and I got an error when reproducing the example code for the filter functionality:

`t = Table(name = ["Alice", "Bob", "Charlie"], age = [25, 42, 37])`

```
Table with 2 columns and 3 rows:
     name     age
   ┌─────────────
 1 │ Alice    25
 2 │ Bob      42
 3 │ Charlie  37
```

`filter(row -> row.age > 40, t)`

```
ERROR: MethodError: objects of type BitVector are not callable
Use square brackets [] for indexing an Array.
Stacktrace:
 [1] top-level scope
```

**Comment by andyferris** [comment]
OK - I can't reproduce this. Which version of typed tables are you using? You can get `status` in `pkg>` mode by typing `]st` at the REPL. The latest release is 1.3.0.

![image](https://user-images.githubusercontent.com/2974526/124686478-8e9f2100-df16-11eb-9f90-a95e093bad85.png)

**Comment by andyferris** [comment]
(e.g. if you type `]up` does the problem go away?)

**Comment by PatMcFarlane** [comment]
I'm using tables v1.3.0 and Tables v1.4.4.   `]up` didn't fix the problem.

But I tried adding the package to my default project environment and then running this code there and it worked just fine.    So I went back to my project environment removed the TypedTables package and then added it again and now everything works fine.

Sorry to bother you with this.

**Comment by andyferris** [comment]
That's fine - I'm glad it worked out in the end.
