### ISSUE TITLE
`size()` doesn't report correct ncols

### ISSUE THREAD

**Issue by Moelf** [JuliaData/TypedTables.jl#85]
IMO the current definition would only make sense if TypedTables is stored by rows
https://github.com/JuliaData/TypedTables.jl/blob/1c0ef0255cd6d61216c57d568c2d66e120cb46ff/src/Table.jl#L109

```julia
julia> size(UnROOT.innertable(tf))
(61540413,)

julia> typeof(UnROOT.innertable(tf))
TypedTables.Table{NamedTuple{(:Muon_phi
```

we should probably go over some interfaces to make sure the table looks like a table (i.e. `ndims == 2`, `size` has two elements)

**Comment by Moelf** [comment]
I think I get it now, the issue is we don't want broadcast to treat the table as a matrix, we want to be treated as a vector of namedtuple (for the speed)

**Comment by andyferris** [comment]
> (for the speed)

It's more for the semantics. We `map` rows and `filter` rows and `reduce` over rows, and we can define `innerjoin` over things that iterate rather than just tables in particular. It is intentially a nested container.
